## Imports / Data Load
- Analyze data to support data modeling and cleaning decisions

In [1]:
# Imports
from __future__ import annotations
from typing import Tuple, List, Union
from pathlib import Path
import duckdb
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None)

# Visuals
import matplotlib.pyplot as plt
import seaborn as sns

# Printing
from rich import print

# Local db path
LOCAL_DB = Path("../data/local_db/ledger.duckdb")

# Connect to DuckDB
con = duckdb.connect(str(LOCAL_DB))

# Load the raw data from the `ledger_raw` table
query = "SELECT * FROM ledger_raw"
df = con.execute(query).df()

# Replace blanks / whitespace with NaN
df.replace(r"^\s*$", np.nan, regex=True, inplace=True)

df.sample(5)

,AGENCYNBR,AGENCYNAME,LEDGER,FISCAL_YEAR,ACCOUNTING_PERIOD,FUND_CODE,FUNDDESCR,CLASS_FLD,CLASSDESCR,DEPTID,DEPTDESCR,ACCOUNT,ACCTDESCR,OPERATING_UNIT,OPERUNITDESCR,PRODUCT,PRODUCTDESCR,PROGRAM_CODE,PGMDESCR,BUDGET_REF,CHARTFIELD1,CF1DESCR,CHARTFIELD2,CF2DESCR,PROJECT_ID,PROJDESCR,POSTED_TOTAL_AMT,ACTIVITY,ACTVDESCR,RESTYPE,RESDESCR,RCAT,RCATDESCR,RSUBCAT,RSUBCATDESCR,ROWID
6563905,4700,INDIGENT DEFENSE SYSTEM,ACTUALS,2026.0,6.0,1000,General Fund - No Divisions,20000,Indigent Defense System Rev Fd,2000200,Executive,542120,Library Resources-Textbooks,NaN,NaN,NaN,NaN,B0003,NaN,26,NaN,NaN,NaN,NaN,NaN,NaN,1935.36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AAJsAKAJuAALZC0AAq
1237143,45200,MENTAL HEALTH AND SUBSTANCE ABUSE SERV.,ACTUALS,2023.0,5.0,1000,General Fund - No Divisions,41000,Federal Funds,3004111,MHAT Law Enforcement,521310,Travel Reimb.-Non-State Empls.,S7389,NaN,NaN,NaN,A0201,NaN,23,932430000,NaN,NaN,NaN,NaN,NaN,88.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AAJsAKAJRAABjPXAAI
3400412,67700,SUPREME COURT,ACTUALS,2025.0,4.0,1000,General Fund - No Divisions,20500,Supreme Court Revolving Fund,8000001,Court Clerk Operations,515320,Graphic Design Services,NaN,NaN,NaN,NaN,B0003,NaN,25,NaN,NaN,NaN,NaN,NaN,NaN,949.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AAJsAKAJaAAF+3SAAV
5045442,34000,OKLAHOMA STATE DEPARTMENT OF HEALTH,ACTUALS,2025.0,3.0,1000,General Fund - No Divisions,40000,Federal Funds,4040005,CHS Early Intervention,513110,Employer Share-FICA,GY5VM0,NaN,47,NaN,C0000,NaN,25,NaN,NaN,NaN,NaN,GYVM,NaN,309.57,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AAJsAKAJaAAGAXuAAI
401935,83000,DEPARTMENT OF HUMAN SERVICES,ACTUALS,2022.0,6.0,1000,General Fund - No Divisions,32100,Fy01 Human Ser Disbursing Fund,NaN,NaN,101000,Cash - Combining Trial Balance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-110526.82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,AAJsAKAHkAALaDGAAH

## Null Values
- Columns that are wholly null (not analyzed further):
  - `['PGMDESCR', 'OPERUNITDESCR', 'RSUBCATDESCR', 'RSUBCAT', 'RCATDESCR',
      'RCAT', 'RESDESCR', 'RESTYPE', 'ACTVDESCR', 'CF1DESCR', 'CF2DESCR',
       'PROJDESCR', 'PRODUCTDESCR']`

In [2]:
# Null counts - most columns are empty - drop
null_values = df.isnull().sum().sort_values(ascending=False)
null_values

PGMDESCR             7087897
OPERUNITDESCR        7087897
RSUBCATDESCR         7087897
RSUBCAT              7087897
RCATDESCR            7087897
RCAT                 7087897
RESDESCR             7087897
RESTYPE              7087897
ACTVDESCR            7087897
CF1DESCR             7087897
CF2DESCR             7087897
PROJDESCR            7087897
PRODUCTDESCR         7087897
CHARTFIELD1          6750278
ACTIVITY             6728104
CHARTFIELD2          5896978
PRODUCT              3299609
PROJECT_ID           3246480
OPERATING_UNIT       2412936
BUDGET_REF            649246
PROGRAM_CODE          527056
DEPTDESCR             512411
DEPTID                512411
ROWID                 373357
CLASSDESCR                45
AGENCYNAME                 0
ACCTDESCR                  0
POSTED_TOTAL_AMT           0
ACCOUNT                    0
CLASS_FLD                  0
FUNDDESCR                  0
FUND_CODE                  0
ACCOUNTING_PERIOD          0
FISCAL_YEAR                0
LEDGER                     0
AGENCYNBR                  0
dtype: int64

In [3]:
# Collect columns that are fully null and drop from the data
row_count, _ = df.shape
cols_to_drop = null_values[null_values == row_count].index
df = df.drop(columns=cols_to_drop)
df.sample(5)

,AGENCYNBR,AGENCYNAME,LEDGER,FISCAL_YEAR,ACCOUNTING_PERIOD,FUND_CODE,FUNDDESCR,CLASS_FLD,CLASSDESCR,DEPTID,DEPTDESCR,ACCOUNT,ACCTDESCR,OPERATING_UNIT,PRODUCT,PROGRAM_CODE,BUDGET_REF,CHARTFIELD1,CHARTFIELD2,PROJECT_ID,POSTED_TOTAL_AMT,ACTIVITY,ROWID
4430948,34000,OKLAHOMA STATE DEPARTMENT OF HEALTH,ACTUALS,2024.0,3.0,1000,General Fund - No Divisions,40000,Federal Funds,4040005,CHS Early Intervention,512110,Insur.Prem-Hlth-Life-State Pln,GY4VM0,70,C0000,24,NaN,NaN,KCPE,24.94,NaN,AAJsAKAJvAAAjzfAAP
5864945,34000,OKLAHOMA STATE DEPARTMENT OF HEALTH,ACTUALS,2025.0,10.0,1000,General Fund - No Divisions,40000,Federal Funds,4020003,IMMUNIZATION,512110,Insur.Prem-Hlth-Life-State Pln,CD12F0,09,A0100,25,NaN,NaN,ARNC,131.91,NaN,AAJsAKAJ+AADyxqAAY
1686285,67000,J.D. MCCARTY CENTER,ACTUALS,2023.0,8.0,1000,General Fund - No Divisions,19301,GRF,1000001,General Operations,512110,Insur.Prem-Hlth-Life-State Pln,NaN,NaN,A0200,23,NaN,NaN,NaN,19604.80,NaN,AAJsAKAJBAAHPzNAAs
2863764,27500,OFFICE OF EDUC. QUALITY & ACCOUNTABILITY,ACTUALS,2024.0,8.0,1000,General Fund - No Divisions,19111,Carryover,8800001,ISD/Data Processing,532160,Rent-Elec Data Processing Eq.,NaN,NaN,C0200,22,NaN,NaN,NaN,-1076.73,NaN,AAJsAKAI8AANSJ5AAs
4499686,34000,OKLAHOMA STATE DEPARTMENT OF HEALTH,ACTUALS,2024.0,3.0,1000,General Fund - No Divisions,19401,GRF- Duties,4010005,CHD Basic Health,513290,St.Match-Ad Fee-Def Contr,KFXW00,69,D0001,24,NaN,NaN,CGPK,7.16,NaN,AAJsAKAJvAAAj+BAAO

## Data Types
- `FISCAL_YEAR`: Cast to int
- `ACCOUNTING_PERIOD`: Cast to int
- `POSTED_TOTAL_AMT`: Cast to float
- `ACTIVITY`: Understand what this column represents (delta?)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7087897 entries, 0 to 7087896
Data columns (total 23 columns):
 #   Column             Dtype
---  ------             -----
 0   AGENCYNBR          int64
 1   AGENCYNAME         str
 2   LEDGER             str
 3   FISCAL_YEAR        float64
 4   ACCOUNTING_PERIOD  float64
 5   FUND_CODE          int64
 6   FUNDDESCR          str
 7   CLASS_FLD          str
 8   CLASSDESCR         str
 9   DEPTID             str
 10  DEPTDESCR          str
 11  ACCOUNT            int64
 12  ACCTDESCR          str
 13  OPERATING_UNIT     str
 14  PRODUCT            str
 15  PROGRAM_CODE       str
 16  BUDGET_REF         str
 17  CHARTFIELD1        str
 18  CHARTFIELD2        str
 19  PROJECT_ID         str
 20  POSTED_TOTAL_AMT   float64
 21  ACTIVITY           str
 22  ROWID              str
dtypes: float64(3), int64(3), str(17)
memory usage: 2.4 GB

## Check One-to-One Relationships (b/w ID and Description Columns)
- `Data Modeling`: Separate out `AGENCYNAME` into an `AGENCY` table
- `Data Cleaning`: Standardize `AGENCYNAME` values 
  - (e.g., "OK. SCHOOL OF SCIENCE & MATH." vs. "OK. SCHOOL OF SCIENCE & MATH")

In [ ]:
def check_one_to_one_relationship(
    column_pair: Union[Tuple[str, str], List[str]], table: str = "LEDGER_RAW"
) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Check for one-to-one relationships between two columns in a table.

    Args:
        column_pair (Union[Tuple[str, str], List[str]]): The two columns to check (column1, column2).
        table (str): The name of the table to query. Defaults to "LEDGER_RAW".

    Returns:
        Tuple[pd.DataFrame, pd.DataFrame]: A summary DataFrame and a detailed DataFrame.
    """
    if len(column_pair) != 2:
        raise ValueError("The 'column_pair' parameter must contain exactly two column names.")

    column1, column2 = column_pair

    # Define queries
    queries = {
        "summary": f"""
            SELECT
                {column1},
                COUNT(DISTINCT {column2}) AS DISTINCT_{column2}
            FROM {table}
            WHERE {column2} IS NOT NULL
            GROUP BY {column1}
            HAVING DISTINCT_{column2} > 1
        """,
        "details": f"""
            SELECT
                DISTINCT {column1}, {column2}, COUNT(*) AS ROW_COUNT
            FROM {table}
            WHERE {column1} IN (
                SELECT {column1}
                FROM {table}
                WHERE {column2} IS NOT NULL
                GROUP BY {column1}
                HAVING COUNT(DISTINCT {column2}) > 1
            )
            AND {column2} IS NOT NULL
            GROUP BY {column1}, {column2}
            ORDER BY {column1}
        """,
    }

    # Execute queries
    summary_df = con.execute(queries["summary"]).df()
    details_df = con.execute(queries["details"]).df()

    if summary_df.empty and details_df.empty:
        print(f"{column_pair=} has 1:1 relationship")

    return summary_df, details_df

In [ ]:
related_column_pairs = [
    ("AGENCYNBR", "AGENCYNAME"),
    ("FUND_CODE", "FUNDDESCR"),
    ("CLASS_FLD", "CLASSDESCR"),
    ("DEPTID", "DEPTDESCR"),
    ("ACCOUNT", "ACCTDESCR"),
    ("OPERATING_UNIT", "OPERUNITDESCR"),
    ("ACTIVITY", "ACTVDESCR"),
]

for column_pair in related_column_pairs:
    print(f"{column_pair=}")
    summary_df, details_df = check_one_to_one_relationship(column_pair)
    display(summary_df)
    display(details_df)

column_pair=('AGENCYNBR', 'AGENCYNAME')

   AGENCYNBR  DISTINCT_AGENCYNAME
0       6000                    2
1      62900                    2
2      47500                    2
3      75500                    2
4      61900                    2
5      80300                    2

    AGENCYNBR                            AGENCYNAME  ROW_COUNT
0        6000        OK DEP AEROSPACE & AERONAUTICS       4821
1        6000       OKLAHOMA AERONAUTICS COMMISSION       1736
2       47500             OK NEW MOTOR VEHICLE COMM       1437
3       47500             OKLA. MOTOR VEHICLE COMM.        700
4       61900        PHYSICIAN MANPOWER TRNG. COMM.       1181
5       61900        HEALTH CARE WORKFORCE TRNG COM       6284
6       62900         OK. SCHOOL OF SCIENCE & MATH.       7603
7       62900          OK. SCHOOL OF SCIENCE & MATH       1814
8       75500          USED MOTOR VEH & MFG HOUSING       2589
9       75500            USED MOTOR VEHICLE & PARTS        568
10      80300        STATEWIDE CHARTER SCHOOL BOARD       1765
11      80300  ST.WIDE VIRTUAL CHARTER SCHOOL BOARD       1231

column_pair=('FUND_CODE', 'FUNDDESCR')

   FUND_CODE  DISTINCT_FUNDDESCR
0       1830                   2

   FUND_CODE                FUNDDESCR  ROW_COUNT
0       1830   Construction  Property        270
1       1830  Construction & Property          6

column_pair=('CLASS_FLD', 'CLASSDESCR')

    CLASS_FLD  DISTINCT_CLASSDESCR
0       47900                    5
1       19711                   17
2       26800                    3
3       19201                    9
4       29500                   12
..        ...                  ...
505     19709                    2
506     53400                    2
507     57600                    3
508     19318                    2
509     57618                    3

[510 rows x 2 columns]

     CLASS_FLD                    CLASSDESCR  ROW_COUNT
0        10000   Constitutional Reserve Fund         95
1        10000  Const. Reserve Fund - Equip.          5
2        10001              CRF Supplemental          5
3        10001      CORE Syst and Legal Svcs          5
4        10001   Constitutional Reserve Fund         20
...        ...                           ...        ...
2860     90500     Payroll Imprest Cash Fund         15
2861     99400           PAYROLL WITHHOLDING          4
2862     99400          Payroll Withholdings        167
2863     99400           Payroll Withholding      19301
2864     99400           payroll withholding         89

[2865 rows x 3 columns]

column_pair=('DEPTID', 'DEPTDESCR')

      DEPTID  DISTINCT_DEPTDESCR
0    1000016                   4
1    7000712                   2
2    2000008                   3
3    2700001                   4
4    2800006                   2
..       ...                 ...
395  8810101                   2
396  0300009                   2
397  8801115                   2
398  0900013                   2
399  2734000                   2

[400 rows x 2 columns]

       DEPTID                     DEPTDESCR  ROW_COUNT
0     0000000                ALL DEPARTMENT          5
1     0000000                All Department         10
2     0100001     Administrative Operations         14
3     0100001            General Operations      10820
4     0100001               Office Activity       2436
...       ...                           ...        ...
1421  9900001             Bonds And Coupons        100
1422  9900001  Native Am.Cult.& Educ. Auth.          3
1423  9900001   Native Am.Cult. Educ. Auth.         32
1424  9900001                Capital Outlay          7
1425  9900001    Central Administration CSP        117

[1426 rows x 3 columns]

column_pair=('ACCOUNT', 'ACCTDESCR')

    ACCOUNT  DISTINCT_ACCTDESCR
0    483631                   2
1    428199                   2
2    431305                   2
3    433141                   2
4    422975                   2
..      ...                 ...
72   425421                   2
73   476101                   2
74   476131                   2
75   422155                   2
76   425436                   2

[77 rows x 2 columns]

     ACCOUNT                       ACCTDESCR  ROW_COUNT
0     420515   Chemical License, Permit  Fee        398
1     420515  Chemical License, Permit & Fee         23
2     420555   Reg Bds FeesAsmts Commod Sale         90
3     420555  Reg Bds Fees&Asmts Commod Sale          4
4     421386  Fines,CivPenlty,Invst&Adm Cost          3
..       ...                             ...        ...
149   554220    PH Prep & Resp - Pmt & Reimb         69
150   554230   Reimbursement  Repayment -Oth       5236
151   554230  Reimbursement & Repayment -Oth        348
152   561230  Purchase of Sec & Other Invest         14
153   561230   Purchase of Sec  Other Invest        237

[154 rows x 3 columns]

column_pair=('OPERATING_UNIT', 'OPERUNITDESCR')

column_pair=('OPERATING_UNIT', 'OPERUNITDESCR') has 1:1 relationship

Empty DataFrame
Columns: [OPERATING_UNIT, DISTINCT_OPERUNITDESCR]
Index: []

Empty DataFrame
Columns: [OPERATING_UNIT, OPERUNITDESCR, ROW_COUNT]
Index: []

column_pair=('ACTIVITY', 'ACTVDESCR')

column_pair=('ACTIVITY', 'ACTVDESCR') has 1:1 relationship

Empty DataFrame
Columns: [ACTIVITY, DISTINCT_ACTVDESCR]
Index: []

Empty DataFrame
Columns: [ACTIVITY, ACTVDESCR, ROW_COUNT]
Index: []

## Unique Values
- Data Types
   - Check fields that appear numeric for any non-numeric values (e.g., String, Object, "N/A", "Unknown", etc.)

In [7]:
display(df.select_dtypes(include=["object", "string"]).head(2))
display(df.select_dtypes(include=["int64", "float"]).head(2))

,AGENCYNAME,LEDGER,FUNDDESCR,CLASS_FLD,CLASSDESCR,DEPTID,DEPTDESCR,ACCTDESCR,OPERATING_UNIT,PRODUCT,PROGRAM_CODE,BUDGET_REF,CHARTFIELD1,CHARTFIELD2,PROJECT_ID,ACTIVITY,ROWID
0,STATE OF OKLAHOMA,ACTUALS,General Fund - No Divisions,19100,General Revenue Fund,7999999,Clearing and ASA Department,Business Activity Tax,NaN,NaN,NP000,NaN,NaN,NaN,NaN,NaN,AAJsAKAIoAABFPGAAH
1,STATE OF OKLAHOMA,ACTUALS,General Fund - No Divisions,19100,General Revenue Fund,7999999,Clearing and ASA Department,Vehicle Revenue Tax Stamps,NaN,NaN,NP000,NaN,NaN,NaN,NaN,NaN,AAJsAKAIoAABFPGAAM

,AGENCYNBR,FISCAL_YEAR,ACCOUNTING_PERIOD,FUND_CODE,ACCOUNT,POSTED_TOTAL_AMT
0,0,2022.0,1.0,1000,412175,-256.12
1,0,2022.0,1.0,1000,415181,-4917.17

In [ ]:
def find_non_integer_convertible_values(value):
    """
    Function to filter for values that cannot be converted to integer
    """
    try:
        int(value)
        return False
    except ValueError:
        return True


for col in ["CLASS_FLD", "DEPTID", "ACCOUNT"]:
    unique_values = df[col].unique().tolist()
    non_convertible_values = [val for val in unique_values if find_non_integer_convertible_values(val)]
    print(f"{col=}")
    print(non_convertible_values[:5])

col='CLASS_FLD'

['8090B', '8125A', '8141C', '8131N', '8165A']

col='DEPTID'

[nan]

col='ACCOUNT'

[]